-- 1.  TRANSACTION METHOD PERFORMANCE
SELECT 
    TRANSACTION_METHOD,
    COUNT(*) AS TRANSACTION_COUNT,
    ROUND(SUM(AMOUNT), 2) AS TOTAL_AMOUNT
FROM `debit and credit data`
GROUP BY TRANSACTION_METHOD
ORDER BY TOTAL_AMOUNT DESC;

-- 2.	AMOUNT PER BRANCH
SELECT
  Branch,
  SUM(Amount) AS total_amount
FROM
  `debit and credit data`
GROUP BY
  Branch;

-- 3. TOP 10 CLIENT BY TRANSACION VALUE
SELECT Customer_Name, SUM(Amount) AS total_value
FROM `debit and credit data`
GROUP BY Customer_Name
ORDER BY total_value DESC
LIMIT 10;

-- 4. TOTAL DEBIT VS CREDIT AMOUNT
SELECT 
    TRANSACTION_TYPE,
    COUNT(*) AS TOTAL_TRANSACTIONS,
    ROUND(SUM(AMOUNT), 2) AS TOTAL_AMOUNT
FROM `debit and credit data`
GROUP BY TRANSACTION_TYPE;

-- 5. MONTHLY TRANSACTION SUMMARY
SELECT 
    DATE_FORMAT(TRANSACTION_DATE, '%Y-%m') AS TRANSACTION_MONTH,
    COUNT(*) AS TOTAL_TRANSACTIONS,
    ROUND(SUM(AMOUNT), 2) AS TOTAL_AMOUNT
FROM `debit and credit data`
GROUP BY TRANSACTION_MONTH
ORDER BY TRANSACTION_MONTH;

-- 6. CATEGORY-WISE TRANSACTION BREAKDOWN
SELECT 
    CATEGORY,
    COUNT(*) AS TRANSACTION_COUNT,
    ROUND(SUM(AMOUNT), 2) AS TOTAL_AMOUNT
FROM `debit and credit data`
GROUP BY CATEGORY
ORDER BY TOTAL_AMOUNT DESC;

-- 7.  SUSPICIOUS HIGH-VALUE TRANSACTIONS (E.G., ABOVE 100000)
SELECT *
FROM `debit and credit data`
WHERE AMOUNT > 100000
ORDER BY AMOUNT DESC;

-- 8. TRANSACTION TYPE RATIO PER BRANCH
SELECT 
    BRANCH,
    COUNT(CASE WHEN TRANSACTION_TYPE = 'DEBIT' THEN 1 END) AS DEBIT_COUNT,
    COUNT(CASE WHEN TRANSACTION_TYPE = 'CREDIT' THEN 1 END) AS CREDIT_COUNT,
    ROUND(
        IFNULL(COUNT(CASE WHEN TRANSACTION_TYPE = 'DEBIT' THEN 1 END) / 
               NULLIF(COUNT(CASE WHEN TRANSACTION_TYPE = 'CREDIT' THEN 1 END), 0), 2), 2
    ) AS DEBIT_CREDIT_RATIO
FROM `debit and credit data`
GROUP BY BRANCH
ORDER BY DEBIT_CREDIT_RATIO DESC;

-- 9. CATEGORY-WISE SPENDING TRENDS (ONLY DEBITS)
SELECT 
    CATEGORY,
    COUNT(*) AS TXN_COUNT,
    ROUND(SUM(AMOUNT), 2) AS TOTAL_SPENDING,
    ROUND(AVG(AMOUNT), 2) AS AVG_SPEND_PER_TXN
FROM `debit and credit data`
WHERE TRANSACTION_TYPE = 'DEBIT'
GROUP BY CATEGORY
ORDER BY TOTAL_SPENDING DESC;









